CREATE TABLE IF NOT EXISTS courses (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       course_code VARCHAR(10) NOT NULL UNIQUE,
    title VARCHAR(100) NOT NULL,
    instructor_name VARCHAR(80) NOT NULL,
    category VARCHAR(30) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    duration_weeks INTEGER NOT NULL,
    price DECIMAL(6, 2) NOT NULL,
    description VARCHAR(800) NOT NULL,
    created_at TIMESTAMP NOT NULL
    );